export const SEARCH_PRODUCT_LOADING = "SEARCH_PRODUCT_LOADING";
export const SEARCH_PRODUCT_FAILURE = "SEARCH_PRODUCT_FAILURE";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_INPUT_TEXT = "SEARCH_INPUT_TEXT";