export const USERS_LOADING = "USERS_LOADING";
export const USERS_FAILURE = "USERS_FAILURE";
export const USERS_SUCCESS = "USERS_SUCCESS";

export const USERS_GET_DATA_SUCCESS = "USERS_GET_DATA_SUCCESS";